export const ConfigurationKeys = {
  CLIENT_ID: 'CLIENT_ID',
  CLIENT_SECRET: 'CLIENT_SECRET',
  PORT: 'PORT',
  JWT_SECRET: 'SECRET',
  ISSUER: 'ISSUER',
  RELYING_PARTY_URL: 'RELYING_PARTY_URL',
  STREAM_ID: 'STREAM_ID',
  PRIVATE_KEY_PATH: 'PRIVATE_KEY_PATH',
  PUBLIC_KEY_PATH: 'PUBLIC_KEY_PATH',
  PRIVATE_KEY: 'PRIVATE_KEY',
  PUBLIC_KEY: 'PUBLIC_KEY',
  VERIFICATION_INTERVAL: 'VERIFICATION_INTERVAL',
  VERIFICATION_ENDPOINT_URL: 'VERIFICATION_ENDPOINT_URL',
  AWS_STACK_NAME: 'AWS_STACK_NAME'
}
