name: Deploy Feature Branch

on:
  workflow_dispatch:
  workflow_call:

env:
  AWS_REGION: eu-west-2

jobs:
  deploy-feature:
    name: Deploy
    if: startsWith(github.head_ref, 'feature')
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "Base ref: ${{ github.base_ref }}"

      - name: Download build artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: sam-build
      - name: Setup Python 3.8
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.8'
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@819220f63fb333a9a394dd0a5cab2d8303fd17e2 # v2
      - name: Assume the dev account deployment role
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.GH_ACTIONS_DEV_DEPLOY_ROLE_ARN }}
      - name: Deploy to feature stack in the dev account
        env:
          FEATURE_BRANCH_NAME: ${{ github.event.ref }}
        run: |
          stack_name=$(
            echo ${FEATURE_BRANCH_NAME##*/} | \
            tr -cd '[a-zA-Z0-9-]' | \
            tr '[:upper:]' '[:lower:]' | \
            cut -c -20
          )

          sam deploy \
            --stack-name ${stack_name} \
            --no-fail-on-empty-changeset \
            --resolve-s3 \
            --template-file examples/aws-lambda/template.yaml \
            --config-file examples/aws-lambda/samconfig.toml
